baseurl = "https://jakubjanarek.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Jakub Janarek"
title = "Jakub Janarek"
disqusShortname = "@jakubjanarek"
pluralizelisttitles = false
latestpostcount = 20

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Where I talk my brain out"
copyright = "Copyright Â© 2017 Jakub Janarek"
logofile = "img/logo.jpg"
faviconfile = "img/logo.jpg"
highlightjs = true
mojs = true
progressively = true
align_left = false
lang = "en"
github = "jxub"
email = "jjanarek@gmail.com"
linkedin = "jakub-janarek"
twitter = "jjanarek"
social_banner = "img/banner.png"
posts_navigation = true
extracssfiles = ["css/custom.css"]
extrajsfiles = ["js/custom.js"]
